services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    volumes:
      - product-database:/var/lib/postgresql/data
    networks:
      - product-service-network
    environment:
      POSTGRES_PASSWORD: "products-ms"
      POSTGRES_DB: "productsKeeping"
    ports:
      - "15432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "products-ms@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "products-ms"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - product-service-network

  products-ms:
    build:
      context: .
    container_name: products-ms
    ports:
      - "7077:8080"
    depends_on:
      - pgadmin
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/productsKeeping"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "products-ms"
    networks:
      - product-service-network

networks:
  product-service-network:

volumes:
  product-database: