version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - product-database:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - product-service-network

  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - product-service-network

  products-ms:
    build:
      context: .
    container_name: products-ms
    ports:
      - "7077:8080"
    depends_on:
      - pgadmin
    restart: unless-stopped
    environment:
      PROFILE: ${PROFILE}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE: ${DATABASE}
    networks:
      - product-service-network

networks:
  product-service-network:
    name: product-service-network
  gateway-network:
    external: true
    name: order-management-network

volumes:
  product-database: