package br.com.productmanagement.util.enums;

public enum ProductCategory {

    INFORMATICA, CALCADOS, VESTIARIO, COSMETICOS, FERRAMENTAS, AUDIO, VIDEO,
    COZINHA, CAMA, BANHO, MESA, GAMES, ESCRITORIO, CELULAR, SAUDE, CARRO,
    ILUMINACAO, BEBIDAS, ALIMENTOS, BRINQUEDOS, ELETRODOMESTICOS

}
